### ISSUE TITLE
looping over array/collection or map

### ISSUE THREAD

**Issue by IrfanAli17899** [polybase/polylang#108]
Hi folks, the documentation on polylang is not strong also the explorer doesn't show any intellisense, i was wondering if there is any way i can loop over the array or map just like normal js/ts?

**Comment by timmyjose** [comment]
> Hi folks, the documentation on polylang is not strong also the explorer doesn't show any intellisense, i was wondering if there is any way i can loop over the array or map just like normal js/ts?

Hey @IrfanAli17899, sorry for the late reply. We are currently working on updating the docs for `Polybase` in general, and `Polylang` in particular.

As for your question, yes, we can loop over arrays and maps just like in TypeScript/JavaScript. For example:

```typescript
@public
   collection Person {
       id: string;
       name: string;
       age: number;
 
       constructor (id: string, name: string, age: number) {
           this.id = id;
           this.name = name;
           this.age = age;
       }
 
       // increment the age the given number of times
       function incrementAgeMagically(times: number) {
           for (let i = 0; i < times; i += 1) {
               this.age += 1;
           }
       }
} 
```

More details and examples will be provided in the updated docs soon. Stay tuned!

**Comment by calummoore** [comment]
We now have the new docs, closing this issue. https://polylang.dev
