### ISSUE TITLE
Use borrowed strings for AST with lifetimes from parsing input

### ISSUE THREAD

**Issue by mateuszmlc** [polybase/polylang#2]
This should give a big performance boost because there will be less allocations, at the cost of a little uglier code (lifetimes will permutate everywhere)

**Comment by calummoore** [comment]
Can we do some benchmarks first to determine current performance, so we have something to reference against. Are you basically planning to reuse allocations?

**Comment by mateuszmlc** [comment]
> Can we do some benchmarks first to determine current performance, so we have something to reference against. Are you basically planning to reuse allocations?

Will do some benchmarks before refactoring. Instead of allocating strings for collection names, field names, etc, we can reference slices of the code that is being parsed. Yes, basically reusing the one allocation for the input code string.

**Comment by calummoore** [comment]
Clever 🔥
