### ISSUE TITLE
Polylang v1 - Compiler Progress

### ISSUE THREAD

**Issue by mateuszmlc** [polybase/polylang#27]
- [x] uint32
- [x] uint64
- [ ] int32 (currently: add/sub/mul/div)
- [ ] int64
- [ ] float32
- [ ] float64
- [x] boolean
- [x] string
- [ ] null / nullable types 
- [x] flat structs / contract objects (can't have another struct in a field)
- [ ] ~~tuples~~
- [ ] interfaces
- [x] addition
- [x] subtraction
- [x] multiplication
- [x] division
- [x] modulo
- [x] bitwise shift right
- [x] bitwise shift left
- [ ] bitwise ops
- [x] and (`&&`)
- [x] or
- [x] equality
- [x] not equal
- [x] greater than or equal
- [x] greater than
- [x] less than or equal  (of implemented numbers)
- [x] less than (of implemented numbers)
- [ ] string concatenation
- [x] throwing errors
- [x] Functions
- [x] Function calls
- [x] Return statements
- [x] Break statements
- [x] If statements
- [x] While loops
- [ ] For loops
- [x] Scoping (also gives us an easy way to implement builtin functions)
- [x] Assignment
- [ ] Calling contract functions
  - [x] `this` (needs flat structs)
  - [x] Pass in `this` through the advice tape
  - [x] Pass in args through the advice tape
  - [x] Read out the changed `this` to get the new object
  - [ ] Pass in a hash of `this` and record arguments, compare it to calculated hash from secret inputs
  - [ ] ABI
- [x] Pass another record to a contract function and read out the changed object
- [ ] Function calls between contracts (calling another contract function from one contract function)
  - [ ] `Account(id)` calls, with the needed Account already in context
- [x] Function runner binary, with args passed through the advice tape instead of pushing constants to the stack
- [ ] Remove all unwraps, refactor code
- [ ] Error Diagnostics
  - [ ] Print out the line that threw an error
  - [ ] Print out a stack trace
- [ ] Optimizations
  - [ ] Don't write every expression result to memory
  - [ ] Evaluate constant expressions (like addition with both operands being constants)
  - [ ] Semi-lazy evaluation? This would allow for better use of the stack. Basically generate instructions for expressions right before the result is needed
  - [ ] Use words for storing string bytes in memory
  - [ ] Use adv_pipe to load strings from the advice tape
  - [ ] Don't inline all function calls now that there is a `call` instruction which doesn't inline

Concise feature showcase of what's possible right now:

```typescript
function succ(a: number): number {
  return a + 1;
}

function fib(n: number): number {
  let a = 0;
  let b = 1;
  let i = 0;
  while (i < n) {
    let c = a + b;
    a = b;
    b = c;
    i = i + 1;
  }
  return a;
}

function main(): number {
  if (1 == 1) {
    return succ(5);
  } else {
    return 5;
  }
}

collection Account {
  id: string;
  balance: number;

  # cargo run --bin compile contract:Account function:setBalance <<<'collection Account { id: string; balance: number; function setBalance(newBalance: number) { this.balance = newBalance; } }' 
  function setBalance(newBalance: number) {
    this.balance = newBalance;
  }

  # cargo run --bin compile contract:Account function:transfer <<<'collection Account { id: string; balance: number; function transfer(other: record, amount: number) { assert(this.balance >= amount, '"'Your balance is too low'"'); this.balance = this.balance - amount; other.balance = other.balance + amount; } }'
  function transfer(other: record, amount: number) {
    assert(this.balance >= amount, 'Your balance is too low');

    this.balance = this.balance - amount;
    other.balance = this.balance + amount;
  }
}
```

You can run the compiled assembly by piping it to `cargo run --bin miden-run` and specifying advice tape values with `--advice-tape 0,1,2,3`. For the `transfer` function that would be `cargo run --bin miden-run -- --advice-tape 0,10,0,100,1` (empty id, 10 balance, empty id, 100 balance, 1 amount).

**Comment by calummoore** [comment]
> Semi-lazy evaluation? This would allow for better use of the stack. Basically generate instructions for expressions right before the result is needed

We could request the miden team to allow `movup` to > 16 places, since they now offer unlimited stack depth

**Comment by mateuszmlc** [comment]
> > Semi-lazy evaluation? This would allow for better use of the stack. Basically generate instructions for expressions right before the result is needed
> 
> We could request the miden team to allow `movup` to > 16 places, since they now offer unlimited stack depth

That'd be great. With the point you quoted we wouldn't need to use movup at all. Movup with >16 places would still be useful because we wouldn't need to use memory as much.

**Comment by calummoore** [comment]
Let's keep null consistent with typescript too. Just reviewed the list, and nothing else jumps out as incompatible.
