### ISSUE TITLE
Miden feedback

### ISSUE THREAD

**Issue by calummoore** [polybase/polylang#36]
Let's compile a list of things we would like to see in Miden / feedback for the core team:

 * Return/break statements - currently we use `if` statements to branch early exits, but it would be more performant to exit the code early.
 * Prove miden in miden - this would allow recursive proofs and call other functions (where the proof is generated separately)

**Comment by mateuszmlc** [comment]
- Re: return/break - if a break was to be added, it would also be nice to have a `block .. end` statement, so that you can inline functions
- A fast way to initialize memory with secret inputs / values from the advice tape
- Recursive calls - haven't actually needed this yet

**Comment by calummoore** [comment]
> `block.$blockName .. break.$blockName .. end`

Is the purpose of this to allow you skip back to a defined block, so essentially a fn call? Would we not need a call also in that case? Or are you just thinking of using for scoping? A longer example would be helpful :)

> A fast way to initialize memory with secret inputs / values from the advice tape

So this would be eqv to `adv_push.n` and then `mem_store`?

> A variant of mem_store that swallows/drops the value stack element, i.e. equivalent of mem_store drop

Is this just for convenience, or are you hoping that they might be able to do this in one less cycle?


---

Is the "Strings are expensive" still valid from here https://github.com/polybase/polylang/issues/18? Does using the advice tape / `mem_loadw` help us here?

**Comment by mateuszmlc** [comment]
> Is the purpose of this to allow you skip back to a defined block, so essentially a fn call? Would we not need a call also in that case? Or are you just thinking of using for scoping? A longer example would be helpful :)

A `break.$blockName` would branch to the end of block $blockName, so to the instruction after the block's `end`.

Example:

```
block.blockA
  push.1
  while.true
    break.blockA
  end
end
# break.blockA would move us here
push. ...
```

Same as with `block` in WebAssembly https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Control_flow/block

This would make it possible to inline functions instead of defining procedures. The equivalent procedure for this (if return was a thing) would be:
```
proc.a
  push.1
  while.true
    return
  end
end
```

> So this would be eqv to adv_push.n and then mem_store?

Yes. `adv_push mem_store.1 drop adv_push mem_store.2 drop` would become `adv_to_mem.2.1`, with 2 being the number of field elements to read and 1 being the start addr.

> Is this just for convenience, or are you hoping that they might be able to do this in one less cycle?

Hoping for one less cycle. Not a big deal, just a pattern that I noticed a lot.

> Is the "Strings are expensive" still valid from here https://github.com/polybase/polylang/issues/18? Does using the advice tape / mem_loadw help us here?

`adv_to_mem` and using words (something to look into later for perf) would let us handle a lot longer strings.

**Comment by calummoore** [comment]
> i32 instructions like the u32 ones

Do we not want to ask for `float32` etc at the same time? Would have though that was equally as hard to implement ourselves...

**Comment by mateuszmlc** [comment]
> > A break.$blockName would branch to the end of block $blockName, so to the instruction after the block's end.
> 
> If we have named blocks/breaks then I guess we don't really need the return statement, right? We could just have `block.main`

Yes, same with break for loops.

```
block.loopA
  while.true
    break.loopA
  end
end
```

> Do we not want to ask for float32 etc at the same time? Would have though that was equally as hard to implement ourselves...

Yes. They could also be much faster if implemented as instructions (instead of miden procedures, which is what we have to use), so `i32checked_add` (like u32checked_add)

**Comment by calummoore** [comment]
`movup.n` with >16 places would be useful to allow us to use the stack more often (instead of loading) into memory

(adding here so I don't forget)

**Comment by calummoore** [comment]
Our priority order would be:

1. Named break statements
2. Additional native types - i32, float32 (more perf then adding proc calls)
3. Miden verification (verify proofs in miden)
4. Recursive proc calls
5. Advice tape -> memory optimisation
6. movup.n > 16 places
7. Mem store + drop optimisation


Do you agree with that?

**Comment by mateuszmlc** [comment]
I wouldn't put i32 and float32 on the same level, since I'm almost finished implementing i32 (and it's not too expensive to be a huge issue), I would move it under point 6. Agree with the rest.

**Comment by calummoore** [comment]
So you would leave float32 as 2nd?

**Comment by mateuszmlc** [comment]
> So you would leave float32 as 2nd?

Yes

**Comment by calummoore** [comment]
Feedback has been sent to them here - https://github.com/maticnetwork/miden/discussions/497
